kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dind-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hipster-app-container
spec:
  selector:
    matchLabels:
      app: hipster-app-container
  replicas: 1
  template:
    metadata:
      labels:
        app: hipster-app-container
    spec:
      containers:
      - image: "docker:dind"
        imagePullPolicy: IfNotPresent
        name: dind
        resources:
            requests:
                cpu: 20m
                memory: 512Mi
        securityContext:
            privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ''
        volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-data
        - mountPath: /tmp
          name: dind-tmp
        - mountPath: /etc/docker/certs.d
          name: certs
        - mountPath: /root/hipster-app-containers
          name: hipster-app-containers
      - image: "johnkday/hipster-app-container:latest"
        imagePullPolicy: Always
        name: hipster-app-container
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2376
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /etc/docker/certs.d
          name: certs
        - mountPath: /root/hipster-app-containers
          name: hipster-app-containers
      restartPolicy: Always
      volumes:
      - name: dind-data
        persistentVolumeClaim:
          claimName: dind-vol
      - name: dind-tmp
        emptyDir: {}
      - name: certs
        emptyDir: {}
      - name: hipster-app-containers
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
 name: hipster-app-containers
 labels:
  run: ssh
spec:
 type: NodePort
 ports:
 - port: 22
   targetPort: 22
   protocol: TCP
   nodePort: 32222
 selector:
  app: hipster-app-container
